apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: demo-app
spec:
  encryptedData:
    DB_USER: AgCH+6eg3N9NZeVH4tEGtHLjPPG9nPHwcR1xsVyjUfpAyX0ShpLFALleBY3nGb8kMKzzhP/7E/hOxccH2OzFRNuhUNzP3cOSzFqa0DaejGHmyHgVcpWuBOp8osvnIHUj+LTDQxSf55eit4n6DLyAOiLoVrhHxYBESWJGjEMAHXoZZ4gZ4rfAvkW9zF3nf7cFVSF7qA5pmqEyN27i6UP4Bd5ZBr7RrJDWsA0lDRPWTrEF+Wzh3Kuqo8YWiq9VWXWmaNkZOLlDrmOauc7s5bvaovBG2B07dIJMDhsTcF1fyOj0CcA8MDbWHShWUnzPvssqtB8taAqSk7tpsABG7kLMOmmqpapf98m9AmrbhyE1mo5xp8yeHN/FVU0rsEp0M8FeCHXnAsW2TC6S5735kJBD5eet66ocg+1qdIS4P+xSBNcI3eKFBCazZnf0ps9exEKqRZ/8sfvn/D6nYPTe7VuGUOdohvvLbPCJNzdZSMOe7yiwUakB3nuQPKwfD8Jpk6lvwnPj6Cc5tYXi8z9Xow5tQI3H4z2JbYewY+Qe1ppr34m4TO7BVnVIz23cxyolriANbhx7V5SS5bOUige8/guAvWAHg1NnlnLYma4buNFq7RBas/jGRxe4gKGv5JLfnLMD83hHyMmt+yLd4uCdVRe3JCNjOVCJbVCgjUb/dmwtkd0OdYH38utjkgmwNTfMrOpvPiOesfV6
