apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: demo-app
spec:
  encryptedData:
    DATABASE-PASSWORD: AgAuiDhkaqcQiQkHKRTOinoSzay+RGH46Q3/scmQjbE/7kljTdPvl+mjVVgue0+ea0eXVWXDdoTeIBQpz1RJbap4utoW+/Lrd3I7wLXN40gdNOT0ydIvxIHH3sc0vKeuxNXBIatOKjPr8Riuo4kLb213IEzSAczTUsNhxhwGVWGEH5FjAwbrjw+LaHXEyfom0WrEREBhGY6rcuxm1SsJ6rSZqvTu+PtHpeG9Dzo9Gq6wI9+i1hU2KXNLrD6qyjnHlpbovOND0dPaqkBhZh4ZLyEM1F2h1eY04SYbcows9lQE+hU87Lwwsw8C8G4bnDk+wm2G72LsGZ5lXZQ1smqUgjbKd47EIImQ7dtSBpYDi4YQZEaCxgk2LQ13Z6Z96IjVdnUdVfQYPidh7dZy1Fy8+fukY9Bj0NdFb5uPaUldGP2ZrOGV6pX2n3R5NPq6NCfi1AMx2cAjN2IKx+8HWWpsiazK0EB5H+GPZ9DKj+YAZ9Ll1CSPBnetCHuBJVhsbPEyYA7XIVSXEDQ+V2WuqVVY1elDpjFSO7NHxAbW4ZG4kTLebMFcUBwBoYyf3so2MZteEtIemV5KjmuvPIDdjyVa+it35t177h9aX93xFwjyGgeuTOBeD4eOOKPNnjOgp9s0RSEJs1I6OPuqaTeTHZkOzTWu7Eiopwuy888fWXhydqxEh6YQUtB9eMqrzKNkZQrw2boTdsYKmNnWBg==
