apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials-2
  namespace: demo-app
spec:
  encryptedData:
    DATABASE_PASSWORD_TWO: AgAIZORQi7ExO15Ki6dRAuBSEDBXN09U48LOscDDxFsPLstcwJyc2FFZEmnEt6CBNdB78/uw85MXH3v6jFTbgsTLSlVJwArVvYp5/a83aSIKQX6Y4BhUKuN6gmx5CnOLxyJCXGktrWK//i7I/ENzdLzEYQYAM7+zZjZ2O/f6cZOvi5SVctYsrrajBnihqLm+FvgUMyrmDsTC/4wtr6kVczxAdOCg9oHlxUUJGi3IZhDpup7uZTJQeVo2k/QByWsEy0t0ENbeBK86oDXtUOY8gWg869fy3gfQO+t5wKpxZoWC3T0qZYM1ZDEanLPwjSpWDh5A8vKKMHIzRDbBJCKUiS5ZVAwAU1di1i9rq65PdZjCGOG9ZnbQLAAbuFwlTtxFqO+IqXdrZUw7/v1kNI92FBIsaZPVBZm/cF7wLBk2cv6xGcJjYVxcAbRVsTohN9pkDKQgLD2UP0q8sAIl7FswOEXUr652AFaO9TT5ELUrPjK/rS6mINc/CLSJd3o5hDfid3gDWNDP6P3bwvRmb3eyjVopNrbhyVUp1HdjP6KbOrtonHyPfs+4nabRkU5FgY+KM44DRPgKKgYkb6wa2bbO+aSD7fTnnHWkdCnPN0ESPGjoulsxz+tixRv5BSgfy/22snMZ0y+weVW5SjVAoQ7gd8bOlq+Jr56NqT37NMlrMArcbmWENecMgBqxrDNRiF97lmgvjPmyXt7H
