apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-cred
  namespace: demo-app
spec:
  encryptedData:
    DB_JAVI: AgAoWBZc18sd3QWB1nsTTwR1w2NY8XMksvlSPdbyiP1e3zues2Myjoi0klI9viKTe1lp1rhbL55bNMpZeM/QzjgiW7Z/Er+qDni7hFsLn4dhx2C8f3DbsWnCj8N40i1OHyJ9/WxeE2XGTnDkkBPcX0njd5+F8/I3c78ONF2BCvWHYIYelvs2XUx8FpnvN206yjDDOt0Gwuvj9wW2BHe5q5/hxLa5MeSR8Nuy4fVSXXBKj/gQ+9p3uvs324RU7bVE2Gtyb9Eof0ZQ/gjvS2I8UwUZ4dvIWBU1BToAu8WFZe0EofFwVVGmaeDSgPvJHxrZrv+e6eKLwLQao5+6d9U6bRZSbA9v7+i0hU4mR0+bZFMApJFEgVlWchnxoPqYLvq82uFb4l75pIhNZ8gBTSku4k8CV3VE720e7pDeOd8VyHHT1OBa5mwVW78vtWiL46JDjapFcv8gHb65oT8zhQgWJpLFBnc0+sdNNRT3rFnFyOEj5Bej+MwQWB1ByLQYeIJjTpUUb3QOSPpvLropJJnylE7I/zqO/kuKZjuYynYJ0WC23dQu+9plAZNDb/X+uoxz2NwPnUAKJKarzro8vDKNijaGyE/xKGTvs8frMVTlOdPyu9YQ2iefRmc/AbOyo/tYPeRy7cR0XUArBKLsSDuxgGutOkrurIYano8FhxMHy+Hx+MWIM7glHOuElpEym4SLC2VCs1jD
